In [1]:
j = 5*9
print(j)

45


In [3]:
import numpy as npy
ar = npy.array([2,5,7,9,4])
print(ar)

[2 5 7 9 4]


In [5]:
import numpy as npy
ar = npy.array([[2,5,7,9,4],
                [33,7,23,0,6]])
print(ar)

[[ 2  5  7  9  4]
 [33  7 23  0  6]]


In [6]:
import numpy as npy
ar = npy.array([2,5,7,9,4])
Ar = ar + 5
print(Ar)

[ 7 10 12 14  9]


In [9]:
import pandas as pan
sr = pan.Series([1,4,8,9])
print(sr)

0    1
1    4
2    8
3    9
dtype: int64


In [12]:
import pandas as pan
sr = pan.Series([2,5,7,9,4], index = ['a','b','c','d','e'],)
print(sr)

a    2
b    5
c    7
d    9
e    4
dtype: int64


In [14]:
import pandas as pan
import numpy as py
#ar = npy.array()
sr = pan.Series([2,5,7,9,4], index = ['a','b','c','d','e'], dtype = complex)
print(sr)

a    2.0+0.0j
b    5.0+0.0j
c    7.0+0.0j
d    9.0+0.0j
e    4.0+0.0j
dtype: complex128


In [15]:
import pandas as pan
import numpy as py
ar = npy.array([1,2,3,4,5])
sr = pan.Series(data = ar, index = ['a','b','c','d','e'])
print(sr)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [16]:
import pandas as pan 
df = pan.DataFrame({'Age':[11,15,19],
                   'Color':["Blue","Red","Yellow"]})
print(df)

   Age   Color
0   11    Blue
1   15     Red
2   19  Yellow


In [17]:
import pandas as pan 
df = pan.DataFrame({'Age':[11,15,19],
                   'Color':["Blue","Red","Yellow"]})
df

Age   Color
0   11    Blue
1   15     Red
2   19  Yellow

In [18]:
import pandas as pan 
import numpy as npy
ar = npy.array ([[12,15,18],
                [21,27,83]])
df = pan.DataFrame(data = ar)
df

0   1   2
0  12  15  18
1  21  27  83

In [19]:
import pandas as pan 
import numpy as npy
ar = npy.array ([[12,15,18],
                [21,27,83]])
df = pan.DataFrame(data = ar, columns = ['C1','C2','C3'])
df

C1  C2  C3
0  12  15  18
1  21  27  83

In [20]:
import pandas as pan 
import numpy as npy
ar = npy.array ([[12,15,18],
                [21,27,83]])
df = pan.DataFrame(data = ar, columns = ['C1','C2','C3'],
                  index = ['A', 'B'])
df

C1  C2  C3
A  12  15  18
B  21  27  83